# ansible_playbooks/setup_mail_server.yml
- name: Configure Customer Email Server
  hosts: mail_server_customer
  become: yes
  vars:
    # Các biến này sẽ được truyền từ Jenkinsfile
    # customer_domain: "example.com"
    # customer_email_user: "admin"
    # customer_email_password: "password"
    # nfs_server_private_ip_aws: "10.10.101.10" (IP private của NFS server trên AWS)
    # nfs_export_path_aws: "/srv/nfs_share" (Đường dẫn export trên NFS server AWS)
    # nagios_server_private_ip: "10.10.1.231"
    mail_data_mount_point: "/mnt/mail_data_on_nfs" # Thư mục mount dữ liệu mail

  tasks:
    - name: Update apt cache and install necessary packages
      apt:
        update_cache: yes
        name:
          - postfix
          - dovecot-core
          - dovecot-imapd
          - dovecot-pop3d
          - mailutils
          - nfs-common # Cần thiết để mount NFS
          - nagios-nrpe-server
          - nagios-plugins
        state: present

    - name: Install passlib for password hashing
      pip:
        name: passlib
        state: present
        executable: pip3 # Chỉ định rõ dùng pip3
        
    # ----- Configure NFS Mount for Mail Data from EC2 NFS Server -----
    - name: Ensure mount point for mail data exists (đã tạo trong user_data của EC2)
      file:
        path: "{{ mail_data_mount_point }}" # /mnt/mail_data_on_nfs
        state: directory
        mode: '0777'

    - name: Mount NFS share from AWS EC2 NFS Server (and add to /etc/fstab)
      ansible.posix.mount:
        path: "{{ mail_data_mount_point }}"
        src: "{{ nfs_server_private_ip_aws }}:{{ nfs_export_path_aws }}" # Sử dụng IP private của NFS Server EC2
        fstype: nfs
        opts: "rw,sync,hard,intr,rsize=8192,wsize=8192,timeo=14,vers=4.1,bg" # Thử vers=4 hoặc bỏ nếu có vấn đề
        state: mounted

    # ----- Configure Postfix (Cấu hình cơ bản - Cần mở rộng nhiều) -----
    - name: Configure Postfix system mailname and main mailer type
      debconf:
        name: postfix
        question: "{{ item.question }}"
        value: "{{ item.value }}"
        vtype: string
      loop:
        - { question: 'postfix/mailname', value: "{{ customer_domain }}" }
        - { question: 'postfix/main_mailer_type', value: "'Internet Site'" }
      notify: Restart postfix

    - name: Update Postfix main.cf configurations
      lineinfile:
        path: /etc/postfix/main.cf
        regexp: "^{{ item.key }}\\s*="
        line: "{{ item.key }} = {{ item.value }}"
        state: present
        create: yes
      loop:
        - { key: 'myhostname', value: "mail.{{ customer_domain }}" }
        - { key: 'mydomain', value: "{{ customer_domain }}" }
        - { key: 'myorigin', value: "$mydomain" }
        - { key: 'mydestination', value: "$myhostname, {{ customer_domain }}, localhost.{{ customer_domain }}, localhost" }
        - { key: 'mynetworks', value: "127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128" }
        - { key: 'home_mailbox', value: "Maildir/" } # Dữ liệu mail sẽ trong /home/USER/Maildir hoặc {{ mail_data_mount_point }}/USER/Maildir
      notify: Restart postfix

    # ----- Configure Dovecot (Cấu hình cơ bản - Cần mở rộng nhiều) -----
    - name: Configure Dovecot mail_location to use NFS mount
      lineinfile:
        path: /etc/dovecot/conf.d/10-mail.conf
        regexp: '^mail_location\\s*='
        line: "mail_location = maildir:{{ mail_data_mount_point }}/%u/Maildir" # %u là username, mail sẽ lưu trên NFS
      notify: Restart dovecot

    # ----- Create Email User -----
    - name: Create system user for email with home on NFS share
      user:
        name: "{{ customer_email_user }}"
        password: "{{ customer_email_password | password_hash('sha512') }}"
        shell: /usr/sbin/nologin
        home: "{{ mail_data_mount_point }}/{{ customer_email_user }}" # Thư mục nhà của user trên NFS
        state: present
        create_home: yes
        system: yes
        group: mail # Đảm bảo group 'mail' có quyền ghi vào NFS

    # ----- Configure Nagios NRPE Client -----
    - name: Configure NRPE allowed_hosts
      lineinfile:
        path: /etc/nagios/nrpe.cfg
        regexp: '^allowed_hosts='
        line: "allowed_hosts=127.0.0.1,::1,{{ nagios_server_private_ip }}"
      notify: Restart nrpe

    - name: Enable basic NRPE commands
      lineinfile:
        path: /etc/nagios/nrpe.cfg
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backrefs: yes
      loop:
        - { regexp: '^(#\s*)?command\[check_users\]=.*', line: 'command[check_users]=/usr/lib/nagios/plugins/check_users -w 5 -c 10' }
        - { regexp: '^(#\s*)?command\[check_load\]=.*', line: 'command[check_load]=/usr/lib/nagios/plugins/check_load -r -w .15,.10,.05 -c .30,.25,.20' }
        - { regexp: '^(#\s*)?command\[check_root_disk\]=.*', line: 'command[check_root_disk]=/usr/lib/nagios/plugins/check_disk -w 20% -c 10% -p /' }
        - { regexp: '^(#\s*)?command\[check_mail_data_disk\]=', line: 'command[check_mail_data_disk]=/usr/lib/nagios/plugins/check_disk -w 20% -c 10% -p {{ mail_data_mount_point }}' }
      notify: Restart nrpe

  handlers:
    - name: Restart postfix
      service: name=postfix state=restarted
    - name: Restart dovecot
      service: name=dovecot state=restarted
    - name: Restart nrpe
      service: name=nagios-nrpe-server state=restarted